version: "3"

services:
  app:
    container_name: intranett_app
    build: .
    ports:
      - "3333:3333"
    command: yarn start
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: intranett_db
    environment:
      - POSTGRES_DB=intranett_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

